import type { BaseReturnType } from '@/types';

/**
 * Runtime mode for style generation.
 *
 * - runtime: keep current emotion insertion behavior
 * - extract: consume pre-extracted className map (zero-runtime path)
 */
export type StyleRuntimeMode = 'runtime' | 'extract';

/**
 * Internal extracted style payload.
 *
 * Note: this is a minimal scaffold for the upcoming extractor plugin.
 */
export interface ExtractedStylePayload<T extends BaseReturnType = BaseReturnType> {
  /**
   * Style id generated by compile-time plugin.
   */
  styleId: string;
  /**
   * className map aligned with createStaticStyles return shape.
   */
  styles: T;
}

interface StyleEngineStore {
  mode: StyleRuntimeMode;
  extracted: Map<string, BaseReturnType>;
}

const store: StyleEngineStore = {
  mode: 'runtime',
  extracted: new Map(),
};

export const getStyleRuntimeMode = (): StyleRuntimeMode => store.mode;

export const setStyleRuntimeMode = (mode: StyleRuntimeMode) => {
  store.mode = mode;
};

export const registerExtractedStyles = <T extends BaseReturnType>(
  payload: ExtractedStylePayload<T>,
) => {
  store.extracted.set(payload.styleId, payload.styles);
};

export const getExtractedStyles = <T extends BaseReturnType>(styleId: string): T | undefined => {
  return store.extracted.get(styleId) as T | undefined;
};

export const clearExtractedStyles = () => {
  store.extracted.clear();
};
